version: '2.2'

networks:
  consul_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      consul_net:
        ipv4_address: 172.16.238.20
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vault
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  vault_1:
    depends_on:
      db:
        condition: service_healthy
    image: "vault:1.4.0"
    restart: always
    hostname: "vault_1"
    networks:
      consul_net:
        ipv4_address: 172.16.238.21
    ports:
      - "8201:8200"
    environment:
      VAULT_API_ADDR: http://172.16.238.24
      VAULT_CLUSTER_ADDR: http://172.16.238.21:8201
    volumes:
      - ./vlt:/vault
      - ./vault.hcl:/vault.hcl
    entrypoint: vault server -config=/vault.hcl

  vault_2:
    depends_on:
      db:
        condition: service_healthy
    image: "vault:1.4.0"
    restart: always
    hostname: "vault_2"
    networks:
      consul_net:
        ipv4_address: 172.16.238.22
    ports:
      - "8202:8200"
    environment:
      VAULT_API_ADDR: http://172.16.238.24
      VAULT_CLUSTER_ADDR: http://172.16.238.22:8201
    volumes:
      - ./vlt:/vault
      - ./vault.hcl:/vault.hcl
    entrypoint: vault server -config=/vault.hcl

  vault_3:
    depends_on:
      db:
        condition: service_healthy
    image: "vault:1.4.0"
    restart: always
    hostname: "vault_3"
    networks:
      consul_net:
        ipv4_address: 172.16.238.23
    ports:
      - "8203:8200"
    environment:
      VAULT_API_ADDR: http://172.16.238.24
      VAULT_CLUSTER_ADDR: http://172.16.238.23:8201
    volumes:
      - ./vlt:/vault
      - ./vault.hcl:/vault.hcl
    entrypoint: vault server -config=/vault.hcl

  nginx:
    image: nginx
    networks:
      consul_net:
        ipv4_address: 172.16.238.24
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    command: [nginx, '-g', 'daemon off;']
